package perpus;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.List;
import model.Buku;
import service.PeminjamanService;
import service.MysqlBukuService;
import service.MysqlUserService;
/**
 *
 * @author LENOVO
 */
public class JFrameUtama extends javax.swing.JFrame {
    private MysqlBukuService bukuService = new MysqlBukuService();
    private final PeminjamanService peminjamanService = new PeminjamanService();

    /**
     * Creates new form JFrameUtama
     */
    public JFrameUtama() {
        initComponents();
        loadBukuKeList();
        pasangEventKlikList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listBukuTersedia = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listBukuDipinjam = new javax.swing.JList<>();
        fieldIdUser = new javax.swing.JTextField();
        fieldNamaUser = new javax.swing.JTextField();
        fieldIdBuku = new javax.swing.JTextField();
        btnKembalikanBuku = new javax.swing.JButton();
        btnPinjamBuku = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listBukuTersedia.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listBukuTersedia.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                listBukuTersediaInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listBukuTersedia);

        listBukuDipinjam.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listBukuDipinjam);

        fieldIdUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIdUserActionPerformed(evt);
            }
        });

        btnKembalikanBuku.setText("Kembalikan buku");
        btnKembalikanBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembalikanBukuActionPerformed(evt);
            }
        });

        btnPinjamBuku.setText("Pinjam buku");
        btnPinjamBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinjamBukuActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel1.setText("Buku tersedia");

        jLabel2.setText("Buku tidak tersedia");

        jLabel3.setText("ID =");

        jLabel4.setText("Nama =");

        jLabel5.setText("Nama buku =");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldNamaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldIdBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnRefresh)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnPinjamBuku)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnKembalikanBuku)
                                    .addGap(21, 21, 21)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fieldIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fieldNamaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldIdBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnKembalikanBuku)
                            .addComponent(btnPinjamBuku))
                        .addGap(26, 26, 26)
                        .addComponent(btnRefresh))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadBukuKeList() {
    DefaultListModel<String> modelTersedia = new DefaultListModel<>();
    DefaultListModel<String> modelDipinjam = new DefaultListModel<>();

    List<Buku> semuaBuku = bukuService.getAllBooks();

    for (Buku buku : semuaBuku) {
        String entry = String.format("%s - %s (%s, %d)", 
            buku.getId(), 
            buku.getJudul(), 
            buku.getPenulis(), 
            buku.getTahunTerbit());

        if (buku.isAvailable()) {
            modelTersedia.addElement(entry);
        } else {
            String namaPeminjam = peminjamanService.getNamaPeminjam(buku.getId());
            if (namaPeminjam != null) {
                entry += " | Dipinjam oleh: " + namaPeminjam;
            }
            modelDipinjam.addElement(entry);
        }
    }

    listBukuTersedia.setModel(modelTersedia);
    listBukuDipinjam.setModel(modelDipinjam);
}


    private void pasangEventKlikList() {
    listBukuTersedia.addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            String selected = listBukuTersedia.getSelectedValue();
            if (selected != null && selected.contains(" - ")) {
                String idBuku = selected.split(" - ")[0].trim();
                fieldIdBuku.setText(idBuku);
            }
        }
    });

    listBukuDipinjam.addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            String selected = listBukuDipinjam.getSelectedValue();
            if (selected != null && selected.contains(" - ")) {
                String idBuku = selected.split(" - ")[0].trim();
                fieldIdBuku.setText(idBuku);
            }
        }
    });
}



    private void fieldIdUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIdUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIdUserActionPerformed

    private void btnPinjamBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPinjamBukuActionPerformed
        String selected = listBukuTersedia.getSelectedValue();
    if (selected == null) return;

    // Ambil ID buku dari string, misal ID buku ada di awal
    String idBuku = selected.split(" - ")[0];

    // Misalnya Anda punya nama user dari TextField
    String namaUser = fieldNamaUser.getText().trim(); 
    if (namaUser.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan nama peminjam!");
        return;
    }

    // Tandai buku sebagai tidak tersedia
    bukuService.setAvailability(idBuku, false);

    // Simpan ke daftar peminjaman
    peminjamanService.tambahPeminjaman(idBuku, namaUser);

    // Reload tampilan
    loadBukuKeList();
    }//GEN-LAST:event_btnPinjamBukuActionPerformed

    private void btnKembalikanBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembalikanBukuActionPerformed
        String idBuku = fieldIdBuku.getText().trim();

    if (idBuku.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan ID Buku yang ingin dikembalikan.");
        return;
    }

    boolean sukses = peminjamanService.kembalikanBuku(idBuku);
    if (sukses) {
        JOptionPane.showMessageDialog(this, "Buku berhasil dikembalikan.");
    } else {
        JOptionPane.showMessageDialog(this, "Gagal mengembalikan buku. Pastikan buku sedang dipinjam.");
    }

    loadBukuKeList();
    peminjamanService.hapusPeminjaman(idBuku);

    }//GEN-LAST:event_btnKembalikanBukuActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadBukuKeList();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void listBukuTersediaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_listBukuTersediaInputMethodTextChanged
              // TODO add your handling code here:
    }//GEN-LAST:event_listBukuTersediaInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembalikanBuku;
    private javax.swing.JButton btnPinjamBuku;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JTextField fieldIdBuku;
    private javax.swing.JTextField fieldIdUser;
    private javax.swing.JTextField fieldNamaUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listBukuDipinjam;
    private javax.swing.JList<String> listBukuTersedia;
    // End of variables declaration//GEN-END:variables
}
